### ISSUE TITLE
How to use rezgui?

### ISSUE THREAD

**Issue by HO-COOH** [AcademySoftwareFoundation/rez#1464]
Describe the bug here.

**Environment**
* OS: Windows 10
* Rez version (eg "2.100.0")  ` Rez 2.112.0 from c:\opt\rez\lib\site-packages\rez (python 2.7)`
* Rez python version (output of "rez-python --version") `Python 2.7.18`
 Also tried Python3 with no success

**To Reproduce**
- `pip install pyqt` does not found any packages. 
- `rez-env rezgui` failed with the error message below

**Expected behavior**
Run rezgui

**Actual behavior**
```
11:11:13 ERROR    PackageFamilyNotFoundError: package family not found: PyQt, was required by: rezgui (searched: C:\Users\Test\packages; C:\Users\Test\.rez\packages\int; C:\Users\Test\.rez\packages\ext)
```

**Comment by JeanChristopheMorinPerso** [comment]
The error you get is because you don't have a PyQT Rez package. In general, you don't need to use rez-env to use rez-gui. You could run `c:\opt\rez\Scripts\python -m pip install pyqt` which will install PyQT in rez's virtualenv. Then you'll be able to simply run `rez-gui` without needing to create/use Rez packages.

**Comment by JeanChristopheMorinPerso** [comment]
What error do you get when running rez-gui?

**Comment by HO-COOH** [comment]
@JeanChristopheMorinPerso 
![image](https://user-images.githubusercontent.com/42881734/228332690-1585ea95-e0a0-46f4-b761-c54c312a64e3.png)

**Comment by JeanChristopheMorinPerso** [comment]
You need https://pypi.org/project/Qt.py/ too.

**Comment by HO-COOH** [comment]
Thanks, that solved my issue
