### ISSUE TITLE
'hello' not an internal or external command, not a runnable program or batch file.

### ISSUE THREAD

**Issue by Jack800109** [AcademySoftwareFoundation/rez#1488]
Hello，I'm a newcomer,and I have encountered a problem.
And i checked #469 ,but still couldn't solve the question.
hello_word was be builded and has no error.
So I read wiki but stopped in getting start, because i can't solve this problem.

system: windows 10
`python ./install.py ` and `rez-bind --quickstart` has no error.
All the paths I can find have been added to env path:
> D:\opt\rez\Scripts\rez
> D:\opt\CMake\bin

And created the env `REZ_PACKAGES_PATH`
> %USERPROFILE%\packages

So the problem is :

```
C:\Users\012>rez-env python -- which python
'which' not an internal or external command, not a runnable program or batch file.

C:\Users\012>rez-env hello_world -- hello
'hello' not an internal or external command, not a runnable program or batch file.
```

**Comment by SitiSchu** [comment]
Two things:
1. You need to use `where` instead of `which` since the default shell on Windows is `cmd.exe`
2. From the looks of it, the current hello world example doesn't really work on Windows because windows won't consider `bin/hello` as executable file.

You could try adding `alias('hello', 'python {root}/bin/hello')` to the `commands` in the `package.py` , then build again and see if that works.

**Comment by Jack800109** [comment]
That's true. Thanks
