### ISSUE TITLE
404 links on pages in wiki

### ISSUE THREAD

**Issue by bigly87** [AcademySoftwareFoundation/rez#1524]
I started learning and reading the WIKI, there are so many links for further details or reference for diagram but they get 404 error after clicking on them. Almost all the links on that page are missing. 
Ex:
https://github.com/AcademySoftwareFoundation/rez/blob/aeade211d32e0c792d745dfe88480d7c9ecf628f/wiki/pages/Basic-Concepts.md?plain=1#L85

a missing diagram:

[Consider the following example (the arrows indicate dependencies):](https://github.com/AcademySoftwareFoundation/rez/blob/aeade211d32e0c792d745dfe88480d7c9ecf628f/wiki/pages/Basic-Concepts.md?plain=1#L276)

**Comment by JeanChristopheMorinPerso** [comment]
Hello @bigly87, thanks for reporting this. We are actually working on transitioning the documentation to another system and we will fix this while transitioning to the new system. You can preview the new documentation at https://jcmorin-rez.readthedocs.io/en/latest/ (but note that once it is ready, it'll move to another subdomain).

So I'll close this issue since these links were fixed there.

**Comment by bigly87** [comment]
Nice, thanks @JeanChristopheMorinPerso.
