### ISSUE TITLE
rez-pkg-cache the case of pachage'name

### ISSUE THREAD

**Issue by SKY123C** [AcademySoftwareFoundation/rez#1755]
hi, I found that the capitalization of cli args and package can affect the final result. 
example:
           i inputs a rez_test_pkg, but The name of the folder is Rez_test_pkg，This can lead to errors-"No such variant!".

this I found code in the package of rez
![image](https://github.com/AcademySoftwareFoundation/rez/assets/56999224/77f7c548-1f4d-41e0-bb18-8904acf38492)
because os.listdir will Maintain folder capitalization

**Comment by JeanChristopheMorinPerso** [comment]
Hi @SKY123C, rez is case-sensitive. As far as I understand your issue, this is expected.

**Comment by maxnbk** [comment]
Yes, very late, very intentional followup, but rez being case-sensitive is actually intentional, and I think as of python-3 versions of rez, even unicode characters are supported in package names, if your filesystem does. It is somewhat important to be case-sensitive overall, since rez must work correctly in case-sensitive filesystems. (Hope that clarifies for future readers.)
