### ISSUE TITLE
Python package file comment triggers "unexpected indent" exception

### ISSUE THREAD

**Issue by nrusch** [AcademySoftwareFoundation/rez#325]
Python package definition files seem to have some very strange requirements as far as formatting is concerned (way beyond "Is this valid Python syntax?"). I suspect this is due to some intermediate parsing voodoo that goes beyond just trying to `compile()` it.

The specific issue I've just encountered involves a comment that starts at the beginning of a line inside the `commands` function, rather than indented to match the actual code in the function body. 
This causes `ResolvedContext._execute()` to raise an exception about an unexpected indent.

A simple example:

``` python
# This works
def commands():
    pkgpath = '$PKG_ROOT/foo'
    # env.LD_LIBRARY_PATH.prepend('{pkgpath}/lib')
    end.PATH.prepend('{pkgpath}/bin') 
```

``` python
# This errors
def commands():
    pkgpath = '$PKG_ROOT/foo'
#    env.LD_LIBRARY_PATH.prepend('{pkgpath}/lib')
    end.PATH.prepend('{pkgpath}/bin') 
```

**Comment by nerdvegas** [comment]
This is because the commands() code actually gets parsed out. When you
install a package, its attributes are reasembled into a package definition
once more. It's not simply a case of copying the package.py, because
attributes are added, and variants can be installed into existing packages.

I recall having to deal with some tedious cases related to indenting,
although I don't recall the details now. It could be looked at again and we
can probably get your example above to work; in the meantime though, all
you need to do is keep the indenting flush within the function body, as per
your first example.

A

**Comment by nrusch** [comment]
Thanks Allan. The indentation thing isn't a big deal, but I wanted to make sure this made it on to the radar.
