### ISSUE TITLE
String quotes are swallowed.

### ISSUE THREAD

**Issue by KelSolaar** [AcademySoftwareFoundation/rez#407]
Hi,

An invocation command like the following fails on Windows because the escaped quotes are getting swallowed:

`rez-env maya -- maya -command "print(\"Hello!\")"`

In Maya:
```
print(Hello!);
// Error: print(Hello!); // 
```

Here are a few of other attempts:

`rez-env maya -- maya -command "print(""Hello!"")"`
`rez-env maya -- maya -command "print(^"Hello!^")"`

Every single time the quotes are eaten.

**Comment by KelSolaar** [comment]
I'm being hit by this one again, this time with subprocess/os.system invocation. Anybody can confirm the issue? It is consistent on Windows for me and basically I cannot use any strings in commands.

> os.system("rez-env maya -- maya -command \"print('Hello!')\"")

```
print(""Hello!");
// Error: print(""Hello!"); // 
// Error: Line 1.13: Syntax error // 
```

Summoning Thorsten (@instinct-vfx)! :)

**Comment by instinct-vfx** [comment]
Hm. Not using Maya and have no package yet so can not try this specific case. Generally nested quotes in the shell and in batchfiles are a bit of a mess to get right on windows.

Did you get your first problem fixed then? Because the latter is calling rez i assume it is not being run from within rez. If you are working with rez from python is there any reason why you are not using the API instead of os.system calls. Just curious, not meant as a solution to the problem.

**Comment by instinct-vfx** [comment]
Disclaimer: My testing may be totally not helpful because we are running rez from a central location with a rather complex set of batch wrappers calling each other. Things that work for me do not necessarily work in a standard setup and vice versa :)

**Comment by KelSolaar** [comment]
> Generally nested quotes in the shell and in batchfiles are a bit of a mess to get right on windows.

I think this is what I'm experiencing right now :)

> If you are working with rez from python is there any reason why you are not using the API instead of os.system calls

I certainly could, as this is part of a build script that does many command line things, I used command line calls for consistency. I might give it a whirl though as it will probably help.

**Comment by skral** [comment]
To escape a double quote you need a second double quote on the Windows command line. The backslash escapes it from rez.

`rez-env maya -- maya -command "print(\"\"Hello!\"\"\")"`
`rez-env python -- python -c "print(\"\"Hello!\"\")"`

Maya is even more special it seems because you need triple quotes for some reason.

My approach to figuring things out:
Resolve an environment and test your command in there before running the command through `rez-env`.

`rez-env python` -> `python -c "print(""Hello!"")"`
`rez-env maya` -> `maya -command "print(""Hello!""")"`

When this works it's easier to know what has to be escaped for rez.
