### ISSUE TITLE
Rez pip doesn't handle optional requirements

### ISSUE THREAD

**Issue by adriankrupa** [AcademySoftwareFoundation/rez#475]
Rez 2.17.1 Windows

For example `rez pip --install pytest` installs on windows succesfully with `colorama`, but it's not added to `requires`. In addition right now rez installs PyPi packages with egg-info and not with dist-info and `distlib` doesn't parse optional requirements. 
Maybe `requires` shoud be changed to late binding function to support this optional requirements.

**Comment by instinct-vfx** [comment]
We're not using the official rez-pip here on windows for various reasons. Most notably the way it is implemented to install into a temp directory (using pip's --install-options) enforces use of source packages rather than binary packages if available. This also causes installing as egg rather than with dist-info by the way. On windows this is quite a hassle as building binary extensions has a lot of pre-requisites on the machine used to build and is often non-trivial and also often does not work out of the box.

In addition we want some custom handling to support different python builds for the same version (e.g. the official python is built with VS2008 which makes official binary packages incompatible and we need to be able to deploy binary packages twice to support python hosts that were built using different toolchains. We have a dedicated wrapper package for MSVC versions that allows for that. We detect binary extensions (by checking all installed files for binary extensions like dll / pyd etc. because metadata is often unreliable) and if an extension is binary we add the toolchain used.

We detect optional requirements, but currently set them as non-optional obviously. Well, we handle some of them. They can be pretty diverse and supporting all possible cases seems kind of daunting.

We also have a fair bit of special handling in there (e.g. generated exe files like with bumpversion, we have a custom python version with patched setuptools/distlib wrappers to support non-absolute paths in generated exe wrappers) to support all kinds of specialities and metadata version quirks and all the other things bringing tears to my eyes.

Anyways, i would welcome some more discussion in that area with other windows based people / shops!

Cheers,
Thorsten

**Comment by JeanChristopheMorinPerso** [comment]
It looks like it was fixed by #602
